#!/bin/bash

TARGET=$1
TARGETREBIN=$2
METADIR=$3
METATABLE=$4
PREDTABLE=$5
OUTPUTDIR=$6
SCRIPTSDIR=$7

Rscript $SCRIPTSDIR/VisualizeTargetBins.r $TARGET $TARGETREBIN $OUTPUTDIR
Rscript $SCRIPTSDIR/VisualizeVariantDistribution.r $METADIR $OUTPUTDIR
Rscript $SCRIPTSDIR/VisualizeLogRRatio.r $METATABLE $OUTPUTDIR
Rscript $SCRIPTSDIR/VisualizeEvaluations.r $PREDTABLE $OUTPUTDIR